version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  dwv-react:
    build:
      context: ./dwv-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dwv-react:/usr/src/app
